name: carpooling_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.13.6
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.2.2
  just_audio: ^0.9.36
  firebase_storage: ^11.5.6
  flutter_sound: ^9.2.13
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  flutter_typeahead: ^5.2.0
  http: ^1.3.0
  flutter_localization: ^0.3.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/sounds/notification.mp3
  uses-material-design: true